export default  [
  {
    id: 1,
    postedOn: "2023-10-28",
    title: "iOS Developer",
    company: "Apple",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["SwiftUI", "UiKit", "Core Data"],
    job_link: "https://www.apple.com/careers/in/",
  },
  {
    id: 2,
    postedOn: "2023-10-28",
    title: "iOS Developer",
    company: "Apple",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["SwiftUI", "UiKit", "Core Data"],
    job_link: "https://www.apple.com/careers/in/",
  },
  {
    id: 3,
    postedOn: "2023-10-28",
    title: "iOS Developer",
    company: "Apple",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["SwiftUI", "UiKit", "Core Data"],
    job_link: "https://www.apple.com/careers/in/",
  },
  {
    id: 4,
    postedOn: "2023-10-28",
    title: "iOS Developer",
    company: "Apple",
    type: "Full Time",
    experience: "Mid Level",
    location: "Remote",
    skills: ["SwiftUI", "UiKit", "Core Data"],
    job_link: "https://www.apple.com/careers/in/",
  },
];
